fix(minisat): :rotating_light: Solver.cc : add required spaces
Fixes issue:

```
Compiling: build/release/minisat/core/Solver.o
minisat/core/Solver.cc:995:39: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
  995 |     printf("restarts              : %"PRIu64"\n", starts);
      |                                       ^
      |
minisat/core/Solver.cc:996:42: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
  996 |     printf("conflicts             : %-12"PRIu64"   (%.0f /sec)\n", conflicts   , conflicts   /cpu_time);
      |                                          ^
      |
minisat/core/Solver.cc:997:42: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
  997 |     printf("decisions             : %-12"PRIu64"   (%4.2f %% random) (%.0f /sec)\n", decisions, (float)rnd_decisions*100 / (float)decisions, decisions   /cpu_time);
      |                                          ^
      |
minisat/core/Solver.cc:998:42: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
  998 |     printf("propagations          : %-12"PRIu64"   (%.0f /sec)\n", propagations, propagations/cpu_time);
      |                                          ^
      |
minisat/core/Solver.cc:999:42: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
  999 |     printf("conflict literals     : %-12"PRIu64"   (%4.2f %% deleted)\n", tot_literals, (max_literals - tot_literals)*100 / (double)max_literals);
      |                                          ^
      |
5 errors generated.
make: *** [build/release/minisat/core/Solver.o] Error 1
emmake: error: 'make r' failed (returned 2)

```